package com.nuvomed.dto;

// Generated Oct 29, 2014 11:20:20 AM by Hibernate Tools 3.4.0.CR1


/**
 * BpsAdminInfo generated by hbm2java
 */
public class Tuser implements java.io.Serializable {
   
	private static final long serialVersionUID = -3068132536895816440L;

	
	private int userId;
	//用户帐户ID
	private String cid;
	private TadminUser adminUser;
	private String code;
	private String firstName;
	private String lastName;
	private String otherName;
	private String createdBy;
	private Boolean gender;
	private String birthday;
	
	private String mobile;
	private String email;
	private Boolean free;
	private String location;
	private Integer result;
	private Boolean missingData;
	
	private String clientName;
	
	public Tuser() {
	}
	
	
	public TadminUser getAdminUser() {
		return adminUser;
	}


	public void setAdminUser(TadminUser adminUser) {
		this.adminUser = adminUser;
	}


	public String getClientName() {
		clientName=lastName;
		if(firstName!=null&&!firstName.isEmpty()){
			clientName=clientName+", "+firstName;
		}
		if(otherName!=null&&!otherName.isEmpty()){
			clientName=clientName+" "+otherName;
		}			
		return clientName;	
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	public String getLocation() {
		return location;
	}



	public void setLocation(String location) {
		this.location = location;
	}



	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Boolean getGender() {
		return gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	public String getBirthday() {
		return birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}



	public int getUserId() {
		return userId;
	}



	public void setUserId(int userId) {
		this.userId = userId;
	}



	public String getCode() {
		return code;
	}



	public void setCode(String code) {
		this.code = code;
	}



	public String getOtherName() {
		return otherName;
	}



	public void setOtherName(String otherName) {
		this.otherName = otherName;
	}



	public String getCreatedBy() {
		return createdBy;
	}



	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}



	public String getCid() {
		if(adminUser!=null){
			cid=adminUser.getAdminId();
		}
		return cid;
	}



	public void setCid(String cid) {
		this.cid = cid;
	}



	public String getEmail() {
		return email;
	}



	public void setEmail(String email) {
		this.email = email;
	}



	public Boolean getFree() {
		return free;
	}



	public void setFree(Boolean free) {
		this.free = free;
	}


	public Integer getResult() {
		return result;
	}


	public void setResult(Integer result) {
		this.result = result;
	}


	public Boolean getMissingData() {
		return missingData;
	}


	public void setMissingData(Boolean missingData) {
		this.missingData = missingData;
	}
	

}
